services:
  ndtc.internetlaboratorytimemanagementsystem.webapi:
    image: ${DOCKER_REGISTRY-}ndtc.internetlaboratorytimemanagementsystemwebapi
    build:
      context: .
      dockerfile: NDTC.InternetLaboratoryTimeManagementSystem.WebAPI/Dockerfile
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iltms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
